import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const TRANSLATIONS = {
  en: {
    // Sidebar Navigation Keys
    navOverview: "Command Overview",
    navComplaints: "Complaints Queue",
    navMap: "Live Incident Map",
    navDepartments: "Department Oversight",
    navAnalytics: "City Analytics",
    navAi: "AI Intelligence",
    navPredictions: "Predictive Intelligence",
    navSla: "SLA Performance",
    navOfficer: "Field Officer Desk",

    // Navbar & Common
    platform: "Platform",
    howItWorks: "How It Works",
    intelligence: "Intelligence",
    trackIssue: "Track Issue",
    reportIssue: "Report Issue",
    reportProblem: "Report Problem",
    login: "Login",
    commandCenter: "Command Center",
    fieldDesk: "Field Officer Desk",
    searchPlaceholder: "Search complaints, wards...",
    exportReport: "Export Report",
    notifications: "Notifications",
    logout: "Log Out",
    welcomeTitle: "CivicOS Municipal Operating System",
    welcomeSubtitle: "Good evening • Here's what is happening across your city today.",
    selectLang: "Language / भाषा / भाषा निवडा",

    // Energy OS & Command Bar Keys
    energyOverview: "OVERVIEW",
    energyGrid: "GRID",
    energyDemand: "DEMAND",
    energySources: "SOURCES",
    energyStorage: "STORAGE",
    energyAnalytics: "ANALYTICS",
    energyDigitalTwin: "DIGITAL TWIN",
    energyAiIntel: "AI INTELLIGENCE",
    energySimulator: "WHAT IF? SIMULATOR",
    energyTitle: "CITY ENERGY COMMAND CENTER",
    energySub: "CIVICOS MUNICIPAL OPERATING SYSTEM • SPATIAL COMMAND CENTER",
    interoperabilityGateway: "National Interoperability Gateway",
    heroSubtitleMain: "Interoperable Civic Infrastructure Operating System",
    launchEnergyOs: "Launch Futuristic Energy OS 4.0",
    totalIngestedReports: "TOTAL INGESTED REPORTS",
    activeIncidentsCount: "ACTIVE INCIDENTS",
    resolvedTodayText: "RESOLVED TODAY",
    resolutionAccuracy: "RESOLUTION ACCURACY",
    enterEnergyOs: "Enter Energy Operating System",
    trackReportedIssue: "Track Reported Issue",
    energyOsShowcaseTitle: "CivicOS Energy Intelligence Platform 4.0",
    energyOsShowcaseSub: "Full-scale futuristic city energy operating system featuring Three.js 3D Spatial Digital Twin, Spacecraft Top Command Bar, real-time node transmission pipeline, SCADA AI Intelligence Assistant, and the signature WHAT IF? Scenario Simulator.",
    onlineStatus: "ONLINE",

    // Telemetry & Grid Metrics
    totalGridLoad: "TOTAL GRID LOAD",
    renewableMix: "RENEWABLE MIX",
    batteryReserve: "BATTERY RESERVE",
    gridHealth: "GRID HEALTH",
    totalEnergy: "TOTAL ENERGY",
    capacityBaseline: "Capacity Baseline",
    currentDemand: "CURRENT DEMAND",
    peakLoadNormal: "Peak Load Normal",
    renewable: "RENEWABLE",
    cleanEnergyMix: "Clean Energy Mix",
    storage: "STORAGE",
    reserveReserves: "Reserve Reserves",
    zeroFaultSync: "Zero Fault Sync",

    // Footer & System Status
    footerTagline: "AI-Powered Civic Intelligence Platform",
    systemStatus: "System Status",
    allEnginesOperational: "All Engines Operational",

    // Hero & Landing Page
    heroBadge: "AI-Powered Municipal Operating System",
    heroTitle: "AI-Powered Municipal Intelligence",
    heroSubtitle: "Transforming unstructured citizen reports into real-time municipal intelligence, automated SLA triage, 3D spatial digital twin monitoring, and verified civic action.",
    reportIssueBtn: "Report Municipal Issue",
    trackIssueBtn: "Track Complaint",
    commandCenterBtn: "Command Center",
    workflowTitle: "From Report to Resolution",
    workflowSubtitle: "Complete 8-step municipal intelligence pipeline — fully automated",

    // 8 Workflow Steps
    step1Title: "Citizen Report",
    step1Desc: "Submit with photo & GPS pin on map",
    step2Title: "AI Classification",
    step2Desc: "LLM extracts category, severity & safety risk",
    step3Title: "Duplicate Detection",
    step3Desc: "Haversine clusters nearby reports (≤500m)",
    step4Title: "Priority Scoring",
    step4Desc: "Deterministic 0–100 urgency formula",
    step5Title: "Department Routing",
    step5Desc: "Auto-assigned to correct municipal dept",
    step6Title: "SLA Countdown",
    step6Desc: "Category-based deadline enforcement",
    step7Title: "Field Resolution",
    step7Desc: "Officer dispatched with GPS navigation",
    step8Title: "Citizen Verified",
    step8Desc: "Citizen confirms fix or reopens the issue",

    // Report Complaint Page
    reportHeaderTitle: "Report a Municipal Problem",
    reportHeaderSub: "AI automatically classifies your issue, assigns priority, and alerts field officers.",
    stepProblem: "1. Problem Details",
    stepLocation: "2. Incident Location",
    stepContact: "3. Citizen Contact",
    stepConfirm: "4. Submit Complaint",
    reportDescTitle: "Describe the Municipal Issue",
    reportDescSub: "Provide clear details so our automated triage system can route your complaint.",
    issueTitleLabel: "Issue Title *",
    issueTitlePlace: "e.g. Large pothole near main college entrance",
    descLabel: "Detailed Description *",
    descPlace: "Describe the exact problem, safety hazards, and street landmarks...",
    catLabel: "Issue Category *",
    autoDetectCategory: "Auto-detect Ward from Location",
    wardLabel: "Municipal Ward",
    wardLabelPrefix: "Ward",
    attachPhoto: "Attach Photo Evidence",
    uploadPhoto: "Upload Photo Evidence",
    removePhoto: "Remove Photo",
    imageAttached: "✔ Photo attached",
    whereIsProblem: "Where is the exact problem located?",
    locationSub: "Drag marker on Leaflet map or search location to set GPS coordinates.",
    whoAreYou: "Citizen Contact Details",
    contactSub: "Provide contact info for status updates.",
    fullName: "Full Name",
    phone: "Phone Number",
    email: "Email Address",
    confirmReportTitle: "Confirm Your Report",
    reviewNotice: "Review your information before submitting to CivicOS authorities.",
    nextBtn: "Next",
    backBtn: "Back",
    submitBtn: "Submit Municipal Complaint",
    submitting: "Submitting report...",
    editBtn: "Edit",
    reportSuccessTitle: "Report Submitted Successfully",
    reportSuccessSub: "Your civic issue has been registered and assigned in the database.",
    requestTrackingId: "CivicOS Request ID",
    assignedDept: "Assigned Department",
    initialStatus: "Initial Status",
    trackThisIssue: "Track This Issue",
    reportAnotherIssue: "Report Another Issue",

    // Location & Map Picker System Keys
    incidentLocation: "Exact Issue Location",
    useGpsBtn: "Use Current GPS Location",
    detectingGps: "Detecting your current location...",
    gpsAccuracy: "GPS Accuracy",
    searchLocationPlace: "Search address, landmark, road, city or PIN code...",
    selectedLocation: "Selected Issue Location",
    address: "Address",
    city: "City / Locality",
    district: "District",
    state: "State",
    pincode: "PIN Code",
    latitude: "Latitude",
    longitude: "Longitude",
    confirmLocationBtn: "Confirm Issue Location",
    locationConfirmed: "Location Confirmed",
    fetchingAddress: "Fetching address...",

    // Categories
    catRoadDamage: "Roads & Public Works",
    catWaterLeakage: "Water Supply & Sewerage",
    catDrainage: "Drainage & Stormwater",
    catGarbage: "Solid Waste & Sanitation",
    catStreetlight: "Electrical & Street Lighting",
    catPublicSafety: "Public Health & Safety",
    catPothole: "Asphalt Pothole Repair",
    catSewage: "Sewer Line & Sanitation",
    catTreeParks: "Parks & Tree Maintenance",
    catOther: "General Municipal Service",

    // Track Complaint Page
    trackHeaderTitle: "Track Civic Complaint Status",
    trackHeaderSub: "Enter your tracking code or phone number to view live SLA progress and field officer updates.",
    searchCodePlace: "Enter Tracking Code (e.g. CIV-138987-644E)...",
    searchBtn: "Track Status",
    statusSubmitted: "Submitted",
    statusAssigned: "Assigned to Dept",
    statusAccepted: "Officer Accepted",
    statusProgress: "Field Work In Progress",
    statusResolved: "Resolved & Fixed",
    verifyQuestion: "Is this issue fixed to your satisfaction?",
    yesBtn: "Yes, Issue Resolved",
    noBtn: "No, Reopen Complaint",
    citizenHistory: "Citizen Portal & History",

    // Admin Overview Dashboard
    overviewTitle: "City Operations Overview",
    overviewSub: "Real-time civic health, priority actions, and municipal intelligence stream",
    demoScenario: "DEMO SCENARIO: Ward 12 Water Pipeline Failure",
    demoDesc: "37 citizen reports aggregated within 500m radius in Ward 12. Priority Score 91/100. SLA countdown active (04:00:00). Auto-routed to Water Department & Field Inspector Rajesh.",
    inspectBtn: "Inspect Incident Cluster #INC-1042",
    totalIngested: "Total Ingested",
    activeIncidents: "Active Incidents",
    slaBreached: "SLA Breached",
    resolvedTodayCount: "Resolved Today",
    resolutionRatePct: "Resolution Rate",
    recentIncidents: "Recent Municipal Complaints",
    mapViewTitle: "Smart City Geospatial Command",
    deptWorkloadRadar: "Department Workload Radar",
    slaCountdownRadar: "SLA Compliance Countdown",
    liveAiStream: "Live AI Event Stream",

    // Department Oversight
    deptEyebrow: "MUNICIPAL DEPARTMENT OVERSIGHT",
    deptTitle: "Regional Workload & Operating Intelligence",
    deptSub: "Live capacity tracking, assigned complaints, SLA compliance rates, and active personnel across all municipal departments.",

    // SLA Monitor
    slaEyebrow: "SERVICE LEVEL AGREEMENT MONITORING",
    slaTitle: "Real-time SLA Target & Escalation Radar",
    slaSub: "Category-based deadline enforcement, live countdown timers, and automated breach prevention alerts.",

    // City Analytics
    analyticsEyebrow: "MUNICIPAL DATA ANALYTICS",
    analyticsTitle: "City-Wide Performance Metrics",
    analyticsSub: "Historical complaint trends, ward-level resolution efficiency, and department capacity benchmarks.",

    // Field Officer Desk
    officerEyebrow: "FIELD OFFICER DISPATCH COMMAND",
    officerTitle: "Active Incident Dispatch Queue",
    officerSub: "Manage assigned tasks, update work status, upload proof photos, and confirm field resolution.",

    // Footer
    copyright: "© 2026 CivicOS Municipal Operating System. All Rights Reserved.",
  },

  hi: {
    // Sidebar Navigation Keys
    navOverview: "कमांड अवलोकन",
    navComplaints: "शिकायत कतार",
    navMap: "लाइव घटना मानचित्र",
    navDepartments: "विभाग निगरानी",
    navAnalytics: "शहर विश्लेषिकी",
    navAi: "एआई इंटेलिजेंस",
    navPredictions: "पूर्वानुमान इंटेलिजेंस",
    navSla: "समय-सीमा प्रदर्शन",
    navOfficer: "फील्ड अधिकारी डेस्क",

    // Navbar & Common
    platform: "प्लेटफ़ॉर्म",
    howItWorks: "यह कैसे काम करता है",
    intelligence: "इंटेलिजेंस",
    trackIssue: "शिकायत ट्रैक करें",
    reportIssue: "समस्या दर्ज करें",
    reportProblem: "समस्या दर्ज करें",
    login: "लॉग इन",
    commandCenter: "कमांड सेंटर",
    fieldDesk: "फील्ड ऑफिसर डेस्क",
    searchPlaceholder: "शिकायतें, वार्ड खोजें...",
    exportReport: "रिपोर्ट एक्सपोर्ट करें",
    notifications: "सूचनाएं",
    logout: "लॉग आउट",
    welcomeTitle: "सिविक-ओएस नगर निगम ऑपरेटिंग सिस्टम",
    welcomeSubtitle: "नमस्ते • आज आपके शहर में हो रही गतिविधियों का विवरण।",
    selectLang: "भाषा चुनें",

    // Energy OS & Command Bar Keys
    energyOverview: "अवलोकन",
    energyGrid: "ग्रिड",
    energyDemand: "मांग",
    energySources: "स्रोत",
    energyStorage: "भंडारण",
    energyAnalytics: "विश्लेषिकी",
    energyDigitalTwin: "डिजिटल ट्विन",
    energyAiIntel: "एआई इंटेलिजेंस",
    energySimulator: "परिदृश्य सिम्युलेटर",
    energyTitle: "शहर ऊर्जा कमांड सेंटर",
    energySub: "सिविक-ओएस नगर निगम ऑपरेटिंग सिस्टम • स्थानिक कमांड सेंटर",
    interoperabilityGateway: "राष्ट्रीय इंटरऑपरेबिलिटी गेटवे",
    heroSubtitleMain: "इंटरऑपरेबल नागरिक ढांचा ऑपरेटिंग सिस्टम",
    launchEnergyOs: "ऊर्जा ओएस 4.0 शुरू करें",
    totalIngestedReports: "कुल दर्ज शिकायतें",
    activeIncidentsCount: "सक्रिय मामले",
    resolvedTodayText: "आज हल किए मामले",
    resolutionAccuracy: "समाधान सटीकता",
    enterEnergyOs: "ऊर्जा ऑपरेटिंग सिस्टम में प्रवेश करें",
    trackReportedIssue: "दर्ज शिकायत ट्रैक करें",
    energyOsShowcaseTitle: "सिविक-ओएस ऊर्जा इंटेलिजेंस प्लेटफॉर्म 4.0",
    energyOsShowcaseSub: "3D डिजिटल ट्विन, कमांड बार, वास्तविक समय प्रसारण पाइपलाइन और एआई सहायक से युक्त पूर्ण शहर ऊर्जा ऑपरेटिंग सिस्टम।",
    onlineStatus: "ऑनलाइन",

    // Telemetry & Grid Metrics
    totalGridLoad: "कुल ग्रिड लोड",
    renewableMix: "अक्षय ऊर्जा मिश्रण",
    batteryReserve: "बैटरी रिजर्व",
    gridHealth: "ग्रिड स्वास्थ्य",
    totalEnergy: "कुल ऊर्जा",
    capacityBaseline: "क्षमता आधार रेखा",
    currentDemand: "वर्तमान मांग",
    peakLoadNormal: "पीक लोड सामान्य",
    renewable: "अक्षय ऊर्जा",
    cleanEnergyMix: "स्वच्छ ऊर्जा मिश्रण",
    storage: "भंडारण",
    reserveReserves: "आरक्षित साठा",
    zeroFaultSync: "शून्य दोष सिंक",

    // Footer & System Status
    footerTagline: "एआई-संचालित नागरिक इंटेलिजेंस प्लेटफॉर्म",
    systemStatus: "सिस्टम स्थिति",
    allEnginesOperational: "सभी इंजन कार्यशील हैं",

    // Hero & Landing Page
    heroBadge: "एआई-संचालित नगर निगम ऑपरेटिंग सिस्टम",
    heroTitle: "एआई-संचालित नगर निगम इंटेलिजेंस",
    heroSubtitle: "सिविक-ओएस हर नागरिक शिकायत को प्राथमिकता, लाइव जीआईएस मानचित्र, त्वरित फील्ड कार्रवाई और सत्यापित समाधान में बदलता है।",
    reportIssueBtn: "नगर निगम समस्या दर्ज करें",
    trackIssueBtn: "शिकायत ट्रैक करें",
    commandCenterBtn: "कमांड सेंटर",
    workflowTitle: "रिपोर्ट से समाधान तक",
    workflowSubtitle: "संपूर्ण 8-चरणीय नगर निगम इंटेलिजेंस प्रणाली — पूर्णतः स्वचालित",

    // 8 Workflow Steps
    step1Title: "नागरिक रिपोर्ट",
    step1Desc: "फोटो और जीपीएस पिन के साथ शिकायत दर्ज करें",
    step2Title: "एआई वर्गीकरण",
    step2Desc: "एआई श्रेणी, गंभीरता और सुरक्षा जोखिम का विश्लेषण करता है",
    step3Title: "डुप्लिकेट पहचान",
    step3Desc: "समीप की शिकायतों की पहचान और क्लस्टरिंग (≤500m)",
    step4Title: "प्राथमिकता स्कोर",
    step4Desc: "0-100 तात्कालीकता स्कोरिंग सूत्र",
    step5Title: "विभाग आवंटन",
    step5Desc: "सही नगर निगम विभाग को स्वचालित आवंटन",
    step6Title: "समय-सीमा काउंटडाउन",
    step6Desc: "श्रेणी अनुसार समय-सीमा का पालन",
    step7Title: "फील्ड समाधान",
    step7Desc: "जीपीएस नेविगेशन के साथ अधिकारी रवाना",
    step8Title: "नागरिक सत्यापन",
    step8Desc: "नागरिक समाधान की पुष्टि करता है या पुनः खोलता है",

    // Report Complaint Page
    reportHeaderTitle: "नगर निगम समस्या दर्ज करें",
    reportHeaderSub: "एआई स्वचालित रूप से आपकी समस्या को वर्गीकृत करता है और अधिकारियों को सचेत करता है।",
    stepProblem: "1. समस्या विवरण",
    stepLocation: "2. घटना का स्थान",
    stepContact: "3. नागरिक संपर्क",
    stepConfirm: "4. शिकायत जमा करें",
    reportDescTitle: "समस्या का विवरण दें",
    reportDescSub: "स्पष्ट विवरण प्रदान करें ताकि हमारी स्वचालित प्रणाली आपकी शिकायत का निवारण कर सके।",
    issueTitleLabel: "समस्या का शीर्षक *",
    issueTitlePlace: "उदा. कॉलेज बस स्टॉप के पास सड़क का बड़ा गड्ढा",
    descLabel: "विस्तृत विवरण *",
    descPlace: "सटीक समस्या, सुरक्षा खतरों और सड़क के मुख्य स्थानों का विवरण दें...",
    catLabel: "समस्या श्रेणी *",
    autoDetectCategory: "स्थान से वार्ड स्वचालित रूप से पहचानें",
    wardLabel: "नगर निगम वार्ड",
    wardLabelPrefix: "वार्ड",
    attachPhoto: "फोटो प्रमाण जोड़ें",
    uploadPhoto: "फोटो प्रमाण अपलोड करें",
    removePhoto: "फोटो हटाएं",
    imageAttached: "✔ फोटो संलग्न किया गया",
    whereIsProblem: "समस्या का सटीक स्थान कहाँ है?",
    locationSub: "जीपीएस निर्देशांक निर्धारित करने के लिए मानचित्र पर मार्कर खींचें या स्थान खोजें।",
    whoAreYou: "नागरिक संपर्क विवरण",
    contactSub: "अद्यतन स्थिति प्राप्त करने के लिए अपनी संपर्क जानकारी प्रदान करें।",
    fullName: "पूरा नाम",
    phone: "फोन नंबर",
    email: "ईमेल पता",
    confirmReportTitle: "अपनी रिपोर्ट की पुष्टि करें",
    reviewNotice: "अधिकारियों को जमा करने से पहले अपनी जानकारी की समीक्षा करें।",
    nextBtn: "आगे बढ़ें",
    backBtn: "पीछे जाएं",
    submitBtn: "नगर निगम शिकायत जमा करें",
    submitting: "जमा हो रहा है...",
    editBtn: "संपादित करें",
    reportSuccessTitle: "रिपोर्ट सफलतापूर्वक दर्ज की गई",
    reportSuccessSub: "आपकी समस्या पंजीकृत और संबंधित विभाग को सौंप दी गई है।",
    requestTrackingId: "सिविक-ओएस ट्रैकिंग आईडी",
    assignedDept: "आवंटित विभाग",
    initialStatus: "प्रारंभिक स्थिति",
    trackThisIssue: "यह शिकायत ट्रैक करें",
    reportAnotherIssue: "दूसरी समस्या दर्ज करें",

    // Location & Map Picker System Keys
    incidentLocation: "घटना का सटीक स्थान",
    useGpsBtn: "वर्तमान जीपीएस स्थान का उपयोग करें",
    detectingGps: "आपका वर्तमान स्थान खोजा जा रहा है...",
    gpsAccuracy: "जीपीएस सटीकता",
    searchLocationPlace: "पता, लैंडमार्क, सड़क, शहर या पिन कोड खोजें...",
    selectedLocation: "चुना गया समस्या स्थान",
    address: "पता",
    city: "शहर / क्षेत्र",
    district: "जिला",
    state: "राज्य",
    pincode: "पिन कोड",
    latitude: "अक्षांश",
    longitude: "देशांतर",
    confirmLocationBtn: "स्थान की पुष्टि करें",
    locationConfirmed: "स्थान की पुष्टि हुई",
    fetchingAddress: "पता प्राप्त किया जा रहा है...",

    // Categories
    catRoadDamage: "सड़कें और सार्वजनिक निर्माण",
    catWaterLeakage: "जल आपूर्ति और जल निकासी",
    catDrainage: "नाली और वर्षा जल",
    catGarbage: "ठोस कचरा प्रबंधन",
    catStreetlight: "विद्युत और स्ट्रीट लाइटिंग",
    catPublicSafety: "जन स्वास्थ्य और सुरक्षा",
    catPothole: "सड़क के खड्डे की मरम्मत",
    catSewage: "सीवर लाइन और स्वच्छता",
    catTreeParks: "पार्क और वृक्ष रखरखाव",
    catOther: "सामान्य नगर निगम सेवा",

    // Track Complaint Page
    trackHeaderTitle: "नागरिक शिकायत की स्थिति ट्रैक करें",
    trackHeaderSub: "लाइव प्रगति और अधिकारी अपडेट देखने के लिए अपना ट्रैकिंग कोड दर्ज करें।",
    searchCodePlace: "ट्रैकिंग कोड दर्ज करें (उदा. CIV-138987-644E)...",
    searchBtn: "स्थिति खोजें",
    statusSubmitted: "जमा किया गया",
    statusAssigned: "विभाग को आवंटित",
    statusAccepted: "अधिकारी द्वारा स्वीकृत",
    statusProgress: "फील्ड कार्य जारी",
    statusResolved: "समाधान संपन्न",
    verifyQuestion: "क्या यह समस्या आपकी संतुष्टि के अनुसार हल हो गई है?",
    yesBtn: "हाँ, समस्या हल हो गई",
    noBtn: "नहीं, शिकायत पुनः खोलें",
    citizenHistory: "नागरिक पोर्टल एवं इतिहास",

    // Admin Overview Dashboard
    overviewTitle: "नगर निगम संचालन अवलोकन",
    overviewSub: "रियल-टाइम नागरिक स्वास्थ्य, प्राथमिकता वाली कार्रवाईयां और नगर निगम इंटेलिजेंस स्ट्रीम",
    demoScenario: "डेमो परिदृश्य: वार्ड 12 जल पाइपलाइन विफलता",
    demoDesc: "वार्ड 12 में 500 मीटर के दायरे में 37 नागरिक रिपोर्टें एकत्र की गईं। प्राथमिकता स्कोर 91/100। एसएलए काउंटडाउन सक्रिय (04:00:00)। जल विभाग और फील्ड इंस्पेक्टर राजेश को स्वचालित रूप से आवंटित।",
    inspectBtn: "घटना क्लस्टर #INC-1042 का निरीक्षण करें",
    totalIngested: "कुल दर्ज शिकायतें",
    activeIncidents: "सक्रिय फील्ड मामले",
    slaBreached: "समय-सीमा उल्लंघन",
    resolvedTodayCount: "आज हल की गई शिकायतें",
    resolutionRatePct: "समाधान दर",
    recentIncidents: "हाल की नगर निगम शिकायतें",
    mapViewTitle: "स्मार्ट सिटी जीियोस्पेशियल कमांड",
    deptWorkloadRadar: "विभाग कार्यभार रडार",
    slaCountdownRadar: "समय-सीमा अनुपालन काउंटडाउन",
    liveAiStream: "लाइव एआई इवेंट स्ट्रीम",

    // Department Oversight
    deptEyebrow: "नगर निगम विभाग निगरानी",
    deptTitle: "क्षेत्रीय कार्यभार और संचालन इंटेलिजेंस",
    deptSub: "सभी नगर निगम विभागों में लाइव क्षमता ट्रैकिंग, आवंटित शिकायतें, और सक्रिय कर्मचारी।",

    // SLA Monitor
    slaEyebrow: "सेवा स्तर समझौता निगरानी",
    slaTitle: "लाइव समय-सीमा लक्ष्य और एस्केलेशन रडार",
    slaSub: "श्रेणी-आधारित समय सीमा प्रवर्तन, लाइव काउंटडाउन टाइमर, और स्वचालित उल्लंघन निवारण चेतावनियां।",

    // City Analytics
    analyticsEyebrow: "नगर निगम डेटा विश्लेषिकी",
    analyticsTitle: "शहर-स्तरीय प्रदर्शन मेट्रिक्स",
    analyticsSub: "ऐतिहासिक शिकायत रुझान, वार्ड-स्तरीय समाधान दक्षता, और विभाग क्षमता मानदंड।",

    // Field Officer Desk
    officerEyebrow: "फील्ड अधिकारी प्रेषण कमांड",
    officerTitle: "सक्रिय घटना प्रेषण कतार",
    officerSub: "आवंटित कार्यों का प्रबंधन करें, कार्य स्थिति अपडेट करें, फोटो अपलोड करें और समाधान की पुष्टि करें।",

    // Footer
    copyright: "© 2026 सिविक-ओएस नगर निगम ऑपरेटिंग सिस्टम। सर्वाधिकार सुरक्षित।",
  },

  mr: {
    // Sidebar Navigation Keys
    navOverview: "कमांड सर्व्हालोकन",
    navComplaints: "तक्रार रांग",
    navMap: "स्मार्ट सिटी जीआयएस नकाशा",
    navDepartments: "महानगरपालिका विभाग देखरेख",
    navAnalytics: "शहर-स्तरीय कामगिरी मोजमाप",
    navAi: "इंटेलिजन्स",
    navPredictions: "पूर्वानुमान इंटेलिजन्स",
    navSla: "मुदत कार्यक्षमता",
    navOfficer: "फील्ड अधिकारी डेस्क",

    // Navbar & Common
    platform: "प्लॅटफॉर्म",
    howItWorks: "हे कसे कार्य करते",
    intelligence: "इंटेलिजन्स",
    trackIssue: "तक्रार ट्रॅक करा",
    reportIssue: "समस्या नोंदवा",
    reportProblem: "समस्या नोंदवा",
    login: "लॉगिन",
    commandCenter: "कमांड सेंटर",
    fieldDesk: "फील्ड ऑफिसर डेस्क",
    searchPlaceholder: "तक्रारी, प्रभाग शोधा...",
    exportReport: "अहवाल एक्सपोर्ट करा",
    notifications: "सूचना",
    logout: "लॉग आउट",
    welcomeTitle: "सिव्हिक-ओएस महानगरपालिका ऑपरेटिंग सिस्टीम",
    welcomeSubtitle: "नमस्कार • आज तुमच्या शहरात घडणाऱ्या घडामोडींचे तपशील.",
    selectLang: "भाषा निवडा",

    // Energy OS & Command Bar Keys
    energyOverview: "सर्व्हालोकन",
    energyGrid: "ग्रिड",
    energyDemand: "मागणी",
    energySources: "स्रोत",
    energyStorage: "साठा",
    energyAnalytics: "विश्लेषण",
    energyDigitalTwin: "डिजिटल ट्विन",
    energyAiIntel: "एआई इंटेलिजन्स",
    energySimulator: "परिदृश्य सिम्युलेटर",
    energyTitle: "शहर ऊर्जा कमांड सेंटर",
    energySub: "सिव्हिक-ओएस महानगरपालिका ऑपरेटिंग सिस्टीम • स्थानिक कमांड सेंटर",
    interoperabilityGateway: "राष्ट्रीय इंटरऑपरेबिलिटी गेटवे",
    heroSubtitleMain: "परस्पर कार्यक्षम नागरी पायाभूत सुविधा ऑपरेटिंग सिस्टीम",
    launchEnergyOs: "ऊर्जा ओएस 4.0 सुरू करा",
    totalIngestedReports: "एकूण प्राप्त तक्रारी",
    activeIncidentsCount: "सक्रिय घटना",
    resolvedTodayText: "आज सुटलेल्या तक्रारी",
    resolutionAccuracy: "निवारण अचूकता",
    enterEnergyOs: "ऊर्जा ऑपरेटिंग सिस्टीममध्ये जा",
    trackReportedIssue: "तक्रार ट्रॅक करा",
    energyOsShowcaseTitle: "सिव्हिक-ओएस ऊर्जा इंटेलिजन्स प्लॅटफॉर्म 4.0",
    energyOsShowcaseSub: "3D डिजिटल ट्विन, कमांड बार, थेट प्रसारण पाइपलाइन आणि एआय सहाय्यकासह संपूर्ण शहर ऊर्जा ऑपरेटिंग सिस्टीम.",
    onlineStatus: "ऑनलाइन",

    // Telemetry & Grid Metrics
    totalGridLoad: "एकूण ग्रिड लोड",
    renewableMix: "नूतनीकरणक्षम ऊर्जा मिश्रण",
    batteryReserve: "बॅटरी साठा",
    gridHealth: "ग्रिड आरोग्य",
    totalEnergy: "एकूण ऊर्जा",
    capacityBaseline: "क्षमता आधार",
    currentDemand: "सध्याची मागणी",
    peakLoadNormal: "पीक लोड सामान्य",
    renewable: "नूतनीकरणक्षम",
    cleanEnergyMix: "स्वच्छ ऊर्जा मिश्रण",
    storage: "साठा",
    reserveReserves: "आरक्षित साठा",
    zeroFaultSync: "शून्य त्रुटी सिंक",

    // Footer & System Status
    footerTagline: "एआय-संचालित नागरी बुद्धिमत्ता प्लॅटफॉर्म",
    systemStatus: "सिस्टीम स्थिती",
    allEnginesOperational: "सर्व इंजिन कार्यरत आहेत",

    // Hero & Landing Page
    heroBadge: "एआई-संचालित महानगरपालिका ऑपरेटिंग सिस्टीम",
    heroTitle: "एआय-संचालित महानगरपालिका बुद्धिमत्ता",
    heroSubtitle: "सिव्हिक-ओएस प्रत्येक नागरिक तक्रारीचे प्राधान्यीकृत घटनांमध्ये, थेट जीआयएस नकाशावर, त्वरित कारवाईत आणि सत्यापित निवारणात रूपांतर करते.",
    reportIssueBtn: "नागरी समस्या नोंदवा",
    trackIssueBtn: "तक्रार ट्रॅक करा",
    commandCenterBtn: "कमांड सेंटर",
    workflowTitle: "तक्रारीपासून निवारणापर्यंत",
    workflowSubtitle: "संपूर्ण 8-टप्प्यांची महापालिका इंटेलिजन्स प्रणाली — पूर्णपणे स्वयंचलित",

    // 8 Workflow Steps
    step1Title: "नागरिक अहवाल",
    step1Desc: "फोटो आणि जीपीएस पिनसह तक्रार नोंदवा",
    step2Title: "एआई वर्गीकरण",
    step2Desc: "एआई श्रेणी, तीव्रता आणि सुरक्षिततेचा धोका विश्लेषित करते",
    step3Title: "डुप्लिकेट शोध",
    step3Desc: "जवळपासच्या तक्रारींची ओळख आणि क्लस्टरिंग (≤500m)",
    step4Title: "प्राधान्य गुणोत्तर",
    step4Desc: "0-100 तातडीचे स्कोरिंग सूत्र",
    step5Title: "विभाग वर्गवारी",
    step5Desc: "योग्य महापालिका विभागाकडे स्वयंचलित वर्गवारी",
    step6Title: "मुदत काउंटडाउन",
    step6Desc: "श्रेणीनुसार मुदत अंमलबजावणी",
    step7Title: "फील्ड निवारण",
    step7Desc: "जीपीएस नेव्हिगेशनसह अधिकारी रवाना",
    step8Title: "नागरिक पडताळणी",
    step8Desc: "नागरिक निवारणाची पुष्टी करतो किंवा पुन्हा उघडतो",

    // Report Complaint Page
    reportHeaderTitle: "महापालिका समस्या नोंदवा",
    reportHeaderSub: "एआई स्वयंचलितपणे तुमच्या समस्येचे वर्गीकरण करते आणि अधिकाऱ्यांना सूचित करते.",
    stepProblem: "1. समस्येचा तपशील",
    stepLocation: "2. घटनेचे ठिकाण",
    stepContact: "3. नागरिक संपर्क",
    stepConfirm: "4. तक्रार सबमिट करा",
    reportDescTitle: "महापालिका समस्येचे वर्णन करा",
    reportDescSub: "स्पष्ट तपशील प्रविष्ट करा जेणेकरून आमची स्वयंचलित प्रणाली तुमची तक्रार योग्य विभागाकडे वर्ग करू शकेल.",
    issueTitleLabel: "समस्येचे शीर्षक *",
    issueTitlePlace: "उदा. महाविद्यालयाच्या बस थांब्याजवळ रस्त्यातील मोठा खड्डा",
    descLabel: "सविस्तर वर्णन *",
    descPlace: "अचूक समस्या, सुरक्षेचा धोका आणि रस्त्यावरील महत्त्वाच्या ठिकाणांचे वर्णन करा...",
    catLabel: "समस्या वर्ग *",
    autoDetectCategory: "ठिकाणावरून प्रभाग स्वयंचलितपणे शोधा",
    wardLabel: "प्रभाग क्रमांक",
    wardLabelPrefix: "प्रभाग",
    attachPhoto: "फोटो पुरावा जोडा",
    uploadPhoto: "फोटो पुरावा अपलोड करा",
    removePhoto: "फोटो काढा",
    imageAttached: "✔ फोटो जोडला गेला",
    whereIsProblem: "समस्या कुठे आहे?",
    locationSub: "जीपीएस अचूक ठिकाण निश्चित करण्यासाठी नकाशावरील पिन हलवा किंवा ठिकाण शोधा.",
    whoAreYou: "नागरिक संपर्क तपशील",
    contactSub: "अद्ययावत माहिती मिळवण्यासाठी संपर्क तपशील प्रविष्ट करा.",
    fullName: "पूर्ण नाव",
    phone: "मोबाईल क्रमांक",
    email: "ईमेल पत्ता",
    confirmReportTitle: "तुमच्या तक्रारीची पुष्टी करा",
    reviewNotice: "सबमिट करण्यापूर्वी माहिती तपासा.",
    nextBtn: "पुढे जा",
    backBtn: "मागे जा",
    submitBtn: "तक्रार सबमिट करा",
    submitting: "सबमिट होत आहे...",
    editBtn: "संपादित करा",
    reportSuccessTitle: "तक्रार यशस्वीरित्या सबमिट केली",
    reportSuccessSub: "तुमची तक्रार नोंदवली गेली असून संबंधित विभागाकडे वर्ग केली आहे.",
    requestTrackingId: "सिव्हिक-ओएस ट्रॅकिंग आयडी",
    assignedDept: "वाटप केलेला विभाग",
    initialStatus: "प्रारंभिक स्थिती",
    trackThisIssue: "ही तक्रार ट्रॅक करा",
    reportAnotherIssue: "दूसरी समस्या नोंदवा",

    // Location & Map Picker System Keys
    incidentLocation: "घटनेचे ठिकाण",
    useGpsBtn: "सध्याचे GPS ठिकाण वापरा",
    detectingGps: "तुमचे ठिकाण शोधले जात आहे...",
    gpsAccuracy: "GPS अचूकता",
    searchLocationPlace: "पत्ता, ठिकाण, रस्ता, शहर किंवा पिन कोड शोधा...",
    selectedLocation: "निवडलेले समस्येचे ठिकाण",
    address: "पत्ता",
    city: "शहर",
    district: "जिल्हा",
    state: "राज्य",
    pincode: "पिन कोड",
    latitude: "अक्षांश",
    longitude: "रेखांश",
    confirmLocationBtn: "ठिकाणाची पुष्टी करा",
    locationConfirmed: "ठिकाणाची पुष्टी झाली",
    fetchingAddress: "पत्ता मिळवला जात आहे...",

    // Categories in Marathi
    catRoadDamage: "रस्ते व सार्वजनिक बांधकाम",
    catWaterLeakage: "पाणी पुरवठा व सांडपाणी",
    catDrainage: "गटारे व पावसाळी पाणी",
    catGarbage: "कचरा व्यवस्थापन व स्वच्छता",
    catStreetlight: "विद्युत व पथदिवे",
    catPublicSafety: "सार्वजनिक आरोग्य व सुरक्षितता",
    catPothole: "रस्त्यातील खड्ड्यांची दुरुस्ती",
    catSewage: "मलनिस्सारण वाहिनी",
    catTreeParks: "बागा व वृक्ष देखभाल",
    catOther: "सामान्य महापालिका सेवा",

    // Track Complaint Page
    trackHeaderTitle: "नागरिक तक्रारीची स्थिती ट्रॅक करा",
    trackHeaderSub: "थेट प्रगती आणि अधिकारी अपडेट्स पाहण्यासाठी तुमचा ट्रॅकिंग कोड प्रविष्ट करा.",
    searchCodePlace: "ट्रॅकिंग कोड प्रविष्ट करा (उदा. CIV-138987-644E)...",
    searchBtn: "स्थिती शोधा",
    statusSubmitted: "सबमिट केले",
    statusAssigned: "विभागाकडे वर्ग",
    statusAccepted: "अधिकाऱ्याने स्वीकारले",
    statusProgress: "काम प्रगतीपथावर",
    statusResolved: "निवारण झाले",
    verifyQuestion: "या समस्येचे आपल्या समाधानानुसार निवारण झाले आहे का?",
    yesBtn: "होय, समस्या सुटली",
    noBtn: "नाही, तक्रार पुन्हा उघडा",
    citizenHistory: "नागरिक पोर्टल आणि इतिहास",

    // Admin Overview Dashboard
    overviewTitle: "शहर महापालिका कामकाज सर्व्हालोकन",
    overviewSub: "थेट नागरी आरोग्य, प्राधान्य कारवाया आणि महापालिका इंटेलिजन्स स्ट्रीम",
    demoScenario: "डेमो देखावा: प्रभाग 12 मधील पाणी पुरवठा वाहिनी बिघाड",
    demoDesc: "प्रभाग 12 मध्ये 500 मीटर परिसरात 37 नागरिक तक्रारी एकत्र आल्या. प्राधान्य स्कोर 91/100. मुदत मोजणी सक्रिय (04:00:00). पाणी पुरवठा विभाग आणि अधिकारी राजेश यांच्याकडे वर्गवारी.",
    inspectBtn: "घटना क्लस्टर #INC-1042 तपासा",
    totalIngested: "एकूण प्राप्त तक्रारी",
    activeIncidents: "सक्रिय घटना",
    slaBreached: "मुदत उल्लंघन",
    resolvedTodayCount: "आज सुटलेल्या तक्रारी",
    resolutionRatePct: "निवारण दर",
    recentIncidents: "अलीकडील तक्रारी",
    mapViewTitle: "स्मार्ट सिटी जीआयएस नकाशा",
    deptWorkloadRadar: "विभाग कार्यभार रडार",
    slaCountdownRadar: "मुदत कार्यक्षमता मोजणी",
    liveAiStream: "थेट एआय घटना फीड",

    // Department Oversight
    deptEyebrow: "महानगरपालिका विभाग देखरेख",
    deptTitle: "प्रादेशिक कार्यभार आणि कार्यप्रणाली",
    deptSub: "सर्व महापालिका विभागांमधील थेट क्षमता ट्रॅकिंग, वाटप केलेल्या तक्रारी आणि सक्रिय कर्मचारी.",

    // SLA Monitor
    slaEyebrow: "सेवा स्तर करार देखरेख",
    slaTitle: "थेट मुदत उद्दिष्ट आणि एस्कॅलेशन रडार",
    slaSub: "श्रेणीनुसार मुदत अंमलबजावणी, थेट काउंटडाउन टाइमर आणि स्वयंचलित उल्लंघन सूचना.",

    // City Analytics
    analyticsEyebrow: "महानगरपालिका डेटा विश्लेषण",
    analyticsTitle: "शहर-स्तरीय कामगिरी मोजमाप",
    analyticsSub: "ऐतिहासिक तक्रार ट्रेंड, प्रभाग-स्तरीय निवारण कार्यक्षमता आणि विभाग क्षमता निकष.",

    // Field Officer Desk
    officerEyebrow: "फील्ड अधिकारी प्रेषण कमांड",
    officerTitle: "सक्रिय घटना प्रेषण रांग",
    officerSub: "नियुक्त कामांचे व्यवस्थापन करा, कामाची स्थिती अपडेट करा, फोटो अपलोड करा आणि निवारणाची पुष्टी करा.",

    // Footer
    copyright: "© 2026 सिव्हिक-ओएस महानगरपालिका ऑपरेटिंग सिस्टीम. सर्व हक्क राखीव.",
  }
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(() => localStorage.getItem('civicos_lang') || 'en');

  const changeLanguage = (newLang) => {
    setLang(newLang);
    localStorage.setItem('civicos_lang', newLang);
  };

  const t = (key) => {
    return TRANSLATIONS[lang]?.[key] || TRANSLATIONS['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
